// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWayTnn_l5YvCtgT8tsHfak9qOviDsHiM',
    appId: '1:573885473144:web:cf4f15504b9be711d1e88d',
    messagingSenderId: '573885473144',
    projectId: 'zoom-clone-26e41',
    authDomain: 'zoom-clone-26e41.firebaseapp.com',
    storageBucket: 'zoom-clone-26e41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwzMeo73IRlfqHSbeiWsKkQ5s_-8nxeG0',
    appId: '1:573885473144:android:9211647a566a8121d1e88d',
    messagingSenderId: '573885473144',
    projectId: 'zoom-clone-26e41',
    storageBucket: 'zoom-clone-26e41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqVsFUTZHgAfms2b-bGTIoPHiqv-1qLkw',
    appId: '1:573885473144:ios:d4b12f83e5d65694d1e88d',
    messagingSenderId: '573885473144',
    projectId: 'zoom-clone-26e41',
    storageBucket: 'zoom-clone-26e41.firebasestorage.app',
    iosBundleId: 'com.example.zoomClone',
  );
}
